# Generated by Django 5.0.6 on 2024-07-18 03:06

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la caja')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion de la caja')),
                ('stock', models.IntegerField(verbose_name='Cantidad en existencias')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio del producto')),
                ('preventa', models.BooleanField(default=False, verbose_name='El producto se encuentra en preventa')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cajas/', verbose_name='Imagen de la caja')),
            ],
        ),
        migrations.CreateModel(
            name='CartaYugioh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la carta')),
                ('descripcion', models.TextField(verbose_name='Descripcion de la carta')),
                ('juego', models.CharField(default='Yu-Gi-Oh!', max_length=50, verbose_name='Juego de cartas')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProductoCartaYugioh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio del producto')),
                ('stock', models.IntegerField(verbose_name='Cantidad de existencias')),
                ('rareza', models.CharField(choices=[('comun', 'Común'), ('rara', 'Rara'), ('super', 'Super rara'), ('ultra', 'Ultra rara'), ('secreta', 'Secreta')], max_length=20, verbose_name='Rareza de la carta')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cartas/', verbose_name='Imagen de la carta')),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.caja', verbose_name='Caja')),
                ('carta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='home.cartayugioh', verbose_name='Carta')),
            ],
        ),
    ]
