# Generated by Django 5.0.6 on 2024-07-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_caja_cajayugioh'),
    ]

    operations = [
        migrations.CreateModel(
            name='cajaMagic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la caja')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion de la caja')),
                ('stock', models.IntegerField(verbose_name='Cantidad en existencias')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio del producto')),
                ('preventa', models.BooleanField(default=False, verbose_name='El producto se encuentra en preventa')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cajas/', verbose_name='Imagen de la caja')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='cartaMagic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la carta')),
                ('descripcion', models.TextField(verbose_name='Descripcion de la carta')),
                ('juego', models.CharField(default='Yu-Gi-Oh!', max_length=50, verbose_name='Juego de cartas')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
