# Generated by Django 5.0.6 on 2024-07-20 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_cajamagic_cartamagic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartamagic',
            name='juego',
            field=models.CharField(default='Magic: The Gathering', max_length=50, verbose_name='Juego de cartas'),
        ),
        migrations.CreateModel(
            name='ProductoCartaMagic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio del producto')),
                ('stock', models.IntegerField(verbose_name='Cantidad de existencias')),
                ('rareza', models.CharField(choices=[('Rara Mitica', 'Rara Mitica'), ('Rara', 'Rara'), ('Infrecuente', 'Infrecuente'), ('Común', 'Común'), ('Tierra básica', 'Tierra básica'), ('Token', 'Token')], max_length=20, verbose_name='Rareza de la carta')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cartas/', verbose_name='Imagen de la carta')),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.cajamagic', verbose_name='Caja')),
                ('carta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.cartamagic', verbose_name='Carta')),
            ],
        ),
    ]
