# Generated by Django 5.0.6 on 2024-08-16 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_cartamagic_juego_productocartamagic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('PROCESANDO', 'Procesando'), ('ENVIADO', 'Enviado'), ('COMPLETADO', 'Completado'), ('REEMBOLSADO', 'Reembolsado'), ('FALLIDO', 'Fallido')], max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
        ),
        migrations.CreateModel(
            name='VentaDetalles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=50, verbose_name='Producto')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('juego', models.CharField(choices=[('Yu-Gi-Oh!', 'Yu-Gi-Oh!'), ('Magic: The Gathering', 'Magic: The Gathering')], max_length=50, verbose_name='TCG')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.venta', verbose_name='Id de la venta')),
            ],
        ),
    ]
