# Generated by Django 5.0.6 on 2024-08-16 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_venta_ventadetalles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VentaDetalles',
            new_name='VentaDetalle',
        ),
    ]
