# Generated by Django 5.0.6 on 2024-08-17 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_ventadetalles_ventadetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventadetalle',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio del producto'),
        ),
    ]
